{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecretName }}
  namespace: dev
  labels:
    app: file-upload-stack
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.data.JWT_SECRET | quote }}
{{- end }}
