helm:
  parameters:
  - name: auth.image.tag
    value: 25458dcbe2db45dbec977d810decfc09db0f4a0d
    forcestring: true
  - name: backend.image.tag
    value: 25458dcbe2db45dbec977d810decfc09db0f4a0d
    forcestring: true
  - name: frontend.image.tag
    value: 25458dcbe2db45dbec977d810decfc09db0f4a0d
    forcestring: true
  - name: image.name
    value: twinkal1710/fileupload-backend
    forcestring: true
