helm:
  parameters:
  - name: auth.image.tag
    value: e46377441b68daebf5b19cbfc4cb2d21566176ae
    forcestring: true
  - name: backend.image.tag
    value: e46377441b68daebf5b19cbfc4cb2d21566176ae
    forcestring: true
  - name: frontend.image.tag
    value: e46377441b68daebf5b19cbfc4cb2d21566176ae
    forcestring: true
  - name: image.name
    value: twinkal1710/fileupload-backend
    forcestring: true
