name: pipeline app cicd inputs

on:
    workflow_dispatch:
      inputs:
        service:
          type: choice
          description: 'Service to test (auth or backend)'
          options:
            - auth
            - backend
          required: true

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code                   # checkout
              uses: actions/checkout@v4
            - name: Set up python                   # BUILD AND UNIT TEST
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Install dependencies
              working-directory: ${{ github.event.inputs.service }}
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest bandit mongomock

            - name: Unit tests
              working-directory: ${{ github.event.inputs.service }}
              run: pytest --maxfail=1 -q

            - name: Code scan (Bandit)
              working-directory: ${{ github.event.inputs.service }}
              run: bandit -r . -ll