name: pipeline app cicd

on:
    push:

env:
  REGISTRY_USER: twinkal1710   # or ghcr.io/yourorg
  IMAGE_PREFIX: fileupload

jobs:
    auth:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code                   # checkout
              uses: actions/checkout@v4
            
            - name: Set up python                   # Install python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies            # Install dependencies
              working-directory: auth
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest bandit mongomock

            - name: Unit tests                      # perform unit tests
              working-directory: auth
              run: pytest --maxfail=1 -q
              
            - name: Code scan (Bandit)              # Code scan using bandit
              working-directory: auth
              run: bandit -r . -ll

    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code                   # checkout
              uses: actions/checkout@v4
            
            - name: Set up python                   # Install python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies            # Install dependencies
              working-directory: backend
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest bandit

            - name: Unit tests                      # perform unit tests
              working-directory: backend
              run: pytest --maxfail=1 -q

            - name: Code scan (Bandit)              # Code scan using bandit
              working-directory: backend
              run: bandit -r . -ll
    frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Lint HTML                       # Lint HTML files
              run: |
                npm install -g htmlhint
                htmlhint "frontend/*.html"

            - name: Validate nginx config syntax    # Validate nginx config syntax
              run: |
                docker run --rm \
                 --add-host=auth:127.0.0.1 \
                 --add-host=backend:127.0.0.1 \
                 -v ${{ github.workspace }}/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro nginx nginx -t

    build-scan-push:
        runs-on: ubuntu-latest
        needs: [auth, backend, frontend]
        strategy:
          matrix:
            service: [auth, backend, frontend]
        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3

            - name: Build Image                       # build docker image
              run: |
                docker build -t $REGISTRY_USER/$IMAGE_PREFIX-${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}
            
            - name: scan image (Trivy)                # scan docker image using trivy
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: ${{env.REGISTRY_USER }}/${{env.IMAGE_PREFIX }}-${{ matrix.service }}:${{ github.sha }}
                format: 'table'
                ignore-unfixed: 'true'
                exit-code: '1'
                severity: 'CRITICAL,HIGH'
            
            - name: Login to registry                 # Login to docker registry
              uses: docker/Login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Push Image                        # push docker image to registry
              run: |
                docker push $REGISTRY_USER/$IMAGE_PREFIX-${{ matrix.service }}:${{ github.sha }}

    update-manifest:
        runs-on: ubuntu-latest
        needs: build-scan-push
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@v4
            with:
              ref: main
          - name: Install yq                    # install yq for yaml manipulation
            run: sudo snap install yq

          - name: Bump image tags in helm values
            run: |
              VALUE=k8s/helm/file-upload-stack/values.yaml
              yq -i '.auth.image.tag = "${{ github.sha }}"' $VALUE
              yq -i '.backend.image.tag = "${{ github.sha }}"' $VALUE
              yq -i '.frontend.image.tag = "${{ github.sha }}"' $VALUE
          
          - name: Commit and push changes
            run: |
              git config --global user.name "github-actions"
              git config --global user.email "github-actions@github.com"
              git add k8s/helm/file-upload-stack/values.yaml
              git commit -m "Bump image tags to $ {{ github.sha }} [skip ci]"
              git push